export const journalQuotes = [
  "You don’t have to control your thoughts. You just have to stop letting them control you. — Dan Millman",
  "Journaling is like whispering to one’s self and listening at the same time. — Mina Murray",
  "The soul always knows what to do to heal itself. The challenge is to silence the mind. — Caroline Myss",
  "Writing is medicine. It is an appropriate antidote to injury. — Julia Cameron",
  "Your story is your power. — Glennon Doyle",
  "Fill your paper with the breathings of your heart. — William Wordsworth",
  "What you are afraid to write is a clear indicator of what you must write. — Unknown",
  "The act of writing is the act of discovering what you believe. — David Hare",
  "Sometimes the most productive thing you can do is relax. — Mark Black",
  "Clarity comes from engagement, not thought. — Marie Forleo",
  "You do not write because you want to say something, you write because you have something to say. — F. Scott Fitzgerald",
  "Keep a journal, and one day it will keep you. — Mae West",
  "The habit of writing for my eye is good practice. It loosens the ligaments. — Virginia Woolf",
  "In the journal I do not just express myself more openly than I could to any person; I create myself. — Susan Sontag",
  "Writing bridges the inner and outer worlds and connects the paths of our lives. — Christina Baldwin",
  "It’s not what you look at that matters, it’s what you see. — Henry David Thoreau",
  "To write something, you have to risk making a fool of yourself. — Anne Rice",
  "Documenting little things daily helps make sense of big things eventually. — Unknown",
  "You must learn to sit with your feelings until they teach you what you need to know. — Brianna Wiest",
  "Journaling is paying attention to the inside for the purpose of living well from the inside out. — Lee Wise",
  "Writing is the painting of the voice. — Voltaire",
  "Start writing, no matter what. The water does not flow until the faucet is turned on. — Louis L’Amour",
  "Write hard and clear about what hurts. — Ernest Hemingway",
  "Almost everything will work again if you unplug it for a few minutes… including you. — Anne Lamott",
  "When you write things down, they sometimes become clearer. — Haruki Murakami",
  "Tears are words that need to be written. — Paulo Coelho",
  "Don’t be afraid to go deep. That’s where the truth lives. — Unknown",
  "A journal is your personal dialogue with life. — Unknown",
  "Writing gives us a place to go when we have no place to go. — bell hooks",
  "Each day's journal entry is a moment captured before it's forgotten. — Unknown"
];
